#!/usr/bin/env node
/*
  node lucide-sync.mjs            copy every icon production's screens import into js/components/icons.js
  node lucide-sync.mjs --dump     the same, and print which were added

  Scans the module's frontend src (and the host components the screen mounts) for
  `from "react-icons/fi"` and `from "lucide-react"` imports, and copies each icon's node list from
  the SAME packages production bundles (the module's node_modules: react-icons 4.12, lucide-react
  0.475). The icon-node arrays are parsed across multiple lines. Icons are data, not design: this
  keeps the prototype's glyphs byte-identical to production's without hand-copying SVG paths.
*/
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PURCHASE_MODULE, STOREFRONT } from './lib/servers.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const NM = path.join(PURCHASE_MODULE, 'node_modules');
const SOURCES = [
  path.join(PURCHASE_MODULE, 'frontend/src'),
  // Host components the screen mounts through capabilities.
  path.join(STOREFRONT, 'src/components/form/selectOption'),
  path.join(STOREFRONT, 'src/components/form/others/DisplayImage.jsx'),
  path.join(STOREFRONT, 'src/components/drawer/RawMaterialReportDrawer.jsx'),
  path.join(STOREFRONT, 'src/components/drawer/RawMaterialReportView.jsx'),
  path.join(STOREFRONT, 'src/components/modal/FormModal.jsx'),
  path.join(STOREFRONT, 'src/components/purchase/CreatePurchaseOrderFromMaterialsModal.jsx'),
  path.join(STOREFRONT, 'src/components/drawer/SourcingOrderDrawer.jsx'),
];

const walk = (p) => (fs.statSync(p).isDirectory() ? fs.readdirSync(p).flatMap((f) => walk(path.join(p, f))) : /\.(jsx?|tsx?)$/.test(p) ? [p] : []);
const fiNames = new Set();
const lucideNames = new Set();
for (const file of SOURCES.filter((p) => fs.existsSync(p)).flatMap(walk)) {
  const src = fs.readFileSync(file, 'utf8');
  for (const m of src.matchAll(/import\s*\{([^}]*)\}\s*from\s*["']react-icons\/fi["']/g)) for (const n of m[1].split(',')) if (n.trim()) fiNames.add(n.trim().split(/\s+as\s+/)[0]);
  for (const m of src.matchAll(/import\s*\{([^}]*)\}\s*from\s*["']lucide-react["']/g)) for (const n of m[1].split(',')) if (n.trim()) lucideNames.add(n.trim().split(/\s+as\s+/)[0]);
}

const attrs = (o) => Object.entries(o).map(([k, v]) => ` ${k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}="${v}"`).join('');
const node = (n) => `<${n.tag}${attrs(n.attr || {})}>${(n.child || []).map(node).join('')}</${n.tag}>`;

const fiSrc = fs.readFileSync(path.join(NM, 'react-icons/fi/index.esm.js'), 'utf8');
const FI = {};
for (const name of [...fiNames].sort()) {
  const m = fiSrc.match(new RegExp(`function ${name} \\(props\\) \\{\\s*return GenIcon\\((\\{.*?\\})\\)\\(props\\);`, 's'));
  if (!m) { console.warn(`react-icons/fi has no ${name}`); continue; }
  FI[name] = JSON.parse(m[1]).child.map(node).join('');
}

// Export name → icon file, from lucide-react's own index (aliases like AlertTriangle live there).
const index = fs.readFileSync(path.join(NM, 'lucide-react/dist/esm/lucide-react.js'), 'utf8');
const fileOf = {};
for (const m of index.matchAll(/export \{([^}]*)\} from '\.\/icons\/([a-z0-9-]+\.js)';/g)) {
  for (const part of m[1].split(',')) { const alias = part.trim().split(/\s+as\s+/)[1]; if (alias) fileOf[alias] = m[2]; }
}
const LUCIDE = {};
for (const name of [...lucideNames].sort()) {
  if (!fileOf[name]) { console.warn(`lucide-react has no ${name}`); continue; }
  const src = fs.readFileSync(path.join(NM, 'lucide-react/dist/esm/icons', fileOf[name]), 'utf8');
  const iconName = src.match(/createLucideIcon\("([^"]+)"/)[1];
  const arr = src.match(/const __iconNode = (\[[\s\S]*?\]);\s*\nconst /)[1];
  // [["path", { d: "…", key: "…" }], …] — keys unquoted: quote them, drop `key`.
  const nodes = JSON.parse(arr.replace(/(\w+):/g, '"$1":'));
  LUCIDE[name] = {
    // lucide's own toKebabCase — the class the component renders (`lucide lucide-<name>`).
    cls: iconName.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase(),
    body: nodes.map(([tag, a]) => { const { key, ...rest } = a; return `<${tag}${attrs(rest)}></${tag}>`; }).join(''),
  };
}

const out = path.join(HERE, '../../js/components/icon-data.js');
fs.writeFileSync(out, `/* GENERATED by tests/parity/lucide-sync.mjs from react-icons ${JSON.parse(fs.readFileSync(path.join(NM, 'react-icons/package.json'))).version} and lucide-react ${JSON.parse(fs.readFileSync(path.join(NM, 'lucide-react/package.json'))).version} — do not edit. */
export const FI = ${JSON.stringify(FI, null, 1)};
export const LUCIDE = ${JSON.stringify(LUCIDE, null, 1)};
`);
console.log(`${Object.keys(FI).length} react-icons/fi, ${Object.keys(LUCIDE).length} lucide → ${path.relative(process.cwd(), out)}`);
