/*
  Checkout — the product's OrderCartModal, in its two steps: review the cart, then choose how it
  is paid. One DOM serves every width: the phone sees cards and a bottom bar, md+ a table and the
  summary sidebar (sales-orders.css → "Checkout" carries the product's own layout rules).

  Admin (proxy) orders open in split-payment mode with the order total on Cash on Delivery.
*/
import { lucide } from '../components/icons.js';
import { esc } from '../components/dom.js';
import { img } from './create-views.js';

const NB = '&nbsp;';
/** cartHelpers.formatMoney — one text node. */
const money = (m, v) => `${m.currency}${NB}${Number(v).toFixed(2)}`;
/** PaymentStep's amounts: Indian grouping, at most two decimals, symbol as its own text. */
const amount = (v) => (Math.round(Math.max(0, Number(v)) * 100) / 100).toLocaleString('en-IN', { maximumFractionDigits: 2 });

/** The payment methods the tenant has switched on, in its order, as the step presents them. */
const METHODS = {
  pod: { icon: 'truck', label: 'Cash on Delivery (COD)', desc: 'Pay in cash upon delivery', input: 'Cash amount' },
  payOnline: { icon: 'credit-card', label: 'Pay Online', desc: 'Cards, UPI, netbanking &amp; wallets', input: 'Amount', badge: 'Online', badgeCls: 'bg-purple-50 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400' },
};
export const paymentMethods = (m) => String(m.appProp.paymentMethods?.isActive || '').split(',').map((s) => s.trim()).filter((id) => METHODS[id]);

/** Totals: a line is its tax-inclusive unit price × qty; tax is backed out of each line. */
export function cartTotals(m, lines) {
  let grand = 0; let net = 0;
  for (const { product, qty, unit } of lines) {
    const line = unit * qty;
    grand += line;
    net += product.tax > 0 ? line / (1 + product.tax / 100) : line;
  }
  return { grand, net, tax: grand - net, units: lines.reduce((s, l) => s + l.qty, 0) };
}

function customerCard(customer) {
  return `<div class="px-4 py-3 lg:px-6 lg:py-4 border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-700/30 flex-shrink-0"><div class="flex items-center gap-2 lg:gap-3">
    <div class="w-8 h-8 lg:w-10 lg:h-10 bg-green-100 dark:bg-green-800 text-green-700 dark:text-green-200 rounded-full flex items-center justify-center text-xs lg:text-sm font-bold shadow-sm flex-shrink-0">${esc(customer.name.charAt(0).toUpperCase())}</div>
    <div class="flex-1 min-w-0 overflow-hidden"><div class="text-xs lg:text-sm font-bold text-gray-900 dark:text-white truncate">${esc(customer.name)}</div><div class="flex flex-wrap items-center gap-x-3 gap-y-0.5 mt-0.5 lg:flex-col lg:items-start lg:gap-0.5">
      <div class="text-[10px] lg:text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">${lucide('phone', { cls: 'w-2.5 h-2.5 lg:w-3 lg:h-3 flex-shrink-0' })}<span>${esc(customer.phone)}</span></div>
      <div class="text-[10px] lg:text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1 min-w-0 max-w-full">${lucide('mail', { cls: 'w-2.5 h-2.5 lg:w-3 lg:h-3 flex-shrink-0' })}<span class="truncate">${esc(customer.email)}</span></div>
    </div></div>
    <div class="flex-shrink-0 relative group"><button class="p-2 lg:p-2.5 rounded-lg transition-all border-2 bg-green-600 text-white hover:bg-green-700 border-green-600 hover:border-green-700 shadow-md cursor-pointer active:scale-95" aria-label="Toggle customer notification" data-testid="customer-info-notify-toggle-desktop" data-status="on">${lucide('bell', { cls: 'w-4 h-4 lg:w-5 lg:h-5' })}</button><div class="notify-tooltip absolute top-full right-0 mt-2 px-3 py-1.5 bg-gray-900 dark:bg-gray-700 text-white text-xs rounded-lg pointer-events-none whitespace-nowrap z-50 shadow-lg transition-opacity opacity-0 group-hover:opacity-100">Customer will be notified about this order. Click to turn OFF<div class="absolute bottom-full right-4 w-0 h-0 border-l-4 border-r-4 border-b-4 border-transparent border-b-gray-900 dark:border-b-gray-700"></div></div></div>
  </div></div>`;
}

function financials(m, t) {
  return `<div class="px-4 py-3 lg:px-6 lg:py-4"><div class="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden dark:border-gray-700 dark:bg-gray-800">
    <div class="flex items-center justify-between px-4 py-3"><div class="flex min-w-0 items-center gap-3"><span class="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-600 dark:bg-blue-900/25 dark:text-blue-300">${lucide('package', { cls: 'h-5 w-5' })}</span><div class="min-w-0"><div class="text-sm font-bold text-gray-900 dark:text-white">Total Units</div><div class="text-xs text-gray-500 dark:text-gray-400">Total quantity of items</div></div></div><div class="flex-shrink-0 text-right"><div class="text-base font-bold text-gray-900 dark:text-white">${t.units}</div><div class="text-xs font-medium text-gray-500 dark:text-gray-400">units</div></div></div>
    <div class="grid grid-cols-2 gap-x-2 gap-y-2 lg:gap-y-2.5 px-4 py-3 border-t border-dashed border-gray-200 dark:border-gray-700"><div class="text-xs lg:text-sm text-gray-500 dark:text-gray-400">Subtotal</div><div class="text-xs lg:text-sm font-semibold text-gray-900 dark:text-white text-right">${money(m, t.net)}</div><div class="text-xs lg:text-sm text-gray-500 dark:text-gray-400">Tax</div><div class="text-xs lg:text-sm font-semibold text-gray-900 dark:text-white text-right">${money(m, t.tax)}</div></div>
    <div class="flex justify-between items-center px-4 py-3 border-t border-dashed border-gray-200 dark:border-gray-700"><div class="text-sm lg:text-base font-bold text-gray-900 dark:text-white">Grand Total</div><div class="text-base lg:text-lg font-bold text-green-600 dark:text-green-400">${money(m, t.grand)}</div></div>
  </div></div>`;
}

function stepper(step) {
  const done = step > 0;
  return `<div class="flex items-center gap-0 flex-shrink-0"><div class="flex items-center">${done
    ? `<div class="w-6 h-6 rounded-full flex items-center justify-center border-2 transition-all flex-shrink-0 bg-green-600 border-green-600 text-white" title="Cart">${lucide('check', { cls: 'w-3 h-3' })}</div><div class="h-px w-5 flex-shrink-0 transition-all bg-green-600"></div>`
    : '<div class="w-6 h-6 rounded-full flex items-center justify-center border-2 transition-all flex-shrink-0 bg-white dark:bg-gray-800 border-green-500 text-green-600 dark:text-green-400" title="Cart"><span class="text-[10px] font-bold leading-none">1</span></div><div class="h-px w-5 flex-shrink-0 transition-all bg-gray-300 dark:bg-gray-600"></div>'}</div>
    <div class="flex items-center"><div class="w-6 h-6 rounded-full flex items-center justify-center border-2 transition-all flex-shrink-0 ${done ? 'bg-white dark:bg-gray-800 border-green-500 text-green-600 dark:text-green-400' : 'bg-white dark:bg-gray-700 border-gray-300 dark:border-gray-500 text-gray-400 dark:text-gray-500'}" title="Payment"><span class="text-[10px] font-bold leading-none">2</span></div></div></div>`;
}

// ── Step 1: the cart ─────────────────────────────────────────────────────────────────────
function cartStep(m, lines) {
  const mobile = lines.map((l, i) => `<div data-testid="cart-item-row-mobile-${l.product.id}" data-status="in-stock" class="overflow-visible rounded-2xl border bg-white shadow-[0_2px_9px_rgba(15,23,42,0.10)] dark:bg-gray-800 border-gray-200 dark:border-gray-600">
      <div class="relative flex min-h-[90px] items-start gap-3 px-3 pb-1.5 pt-3"><div class="h-[72px] w-[72px] flex-shrink-0 overflow-hidden rounded-xl border border-gray-100 bg-gray-50 dark:border-gray-600 dark:bg-gray-700">${img('h-full w-full !object-cover rounded-custom', 72)}</div>
        <div class="min-w-0 flex-1"><div class="truncate text-[15px] font-bold leading-tight text-gray-900 dark:text-white">${esc(l.product.name)}</div><div class="mt-1 truncate text-[11px] text-gray-500 dark:text-gray-400">Art No: <!---->${esc(l.product.articleNo)}</div><div class="mt-2 flex min-w-0 flex-wrap gap-1.5"><span class="max-w-[78px] truncate rounded-md bg-green-50 px-2 py-1 text-[10px] font-medium text-green-600 dark:bg-green-900/25 dark:text-green-400">${esc(l.product.unit)}</span></div></div>
        <div class="flex-shrink-0 pt-1 text-right"><div class="flex gap-2 items-start justify-end"><div class="text-right"><div class="font-bold text-[17px] text-gray-900 dark:text-white leading-tight">${money(m, l.unit)}</div></div><button type="button" data-testid="cart-item-price-edit-btn-mobile-${l.product.id}" class="group flex w-8 flex-shrink-0 items-center justify-center rounded-md transition-colors hover:bg-green-50 dark:hover:bg-green-900/20 h-5" aria-label="Edit price" title="Edit price">${lucide('pen', { cls: 'h-[18px] w-[18px] text-gray-500 group-hover:text-green-600 dark:text-gray-400' })}</button></div></div></div>
      <div class="grid min-h-[58px] grid-cols-[132px_1fr_auto] items-center gap-2 border-t border-gray-100 px-3 py-2 dark:border-gray-700">
        <div class="flex flex-col "><div class="flex items-center border border-gray-200 shadow-[0_2px_6px_rgba(15,23,42,0.10)] dark:border-gray-600 rounded-lg overflow-hidden bg-white dark:bg-gray-800"><button${l.qty <= 1 ? ' disabled=""' : ''} data-act="cart-qty" data-id="${l.product.id}" data-step="-1" data-testid="cart-item-qty-decrement-btn-mobile-${l.product.id}" class="h-10 w-10 text-sm flex-shrink-0 flex items-center justify-center text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-semibold border-r border-gray-200 dark:border-gray-600" title="${l.qty <= 1 ? 'Minimum quantity is 1' : 'Decrease quantity'}" aria-label="Decrease quantity">−</button><input type="tel" inputmode="numeric" pattern="\\d*" id="cart-qty-input-mobile-${i}" data-testid="cart-item-qty-input-mobile-${l.product.id}" autocomplete="off" class="h-10 w-[52px] text-sm text-center font-bold border-0 focus:outline-none focus:ring-0 text-gray-900 dark:text-white bg-transparent" title="Enter quantity" aria-label="Quantity" value="${l.qty}"><button data-act="cart-qty" data-id="${l.product.id}" data-step="1" data-testid="cart-item-qty-increment-btn-mobile-${l.product.id}" class="h-10 w-10 text-sm flex-shrink-0 flex items-center justify-center text-green-600 dark:text-green-400 hover:bg-green-50 dark:hover:bg-gray-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-semibold border-l border-gray-200 dark:border-gray-600" title="Increase quantity" aria-label="Increase quantity">+</button></div></div>
        <div class="min-w-0 text-center text-[11px] leading-tight"><div class="truncate font-bold text-orange-500 dark:text-orange-400">${m.availableStock(l.product)}<!----> avail.</div><div class="mt-0.5 text-[10px] text-gray-500 dark:text-gray-400">In Stock</div></div>
        <div class="flex items-center gap-1.5 text-right"><div class="leading-tight"><div class="text-[10px] font-medium text-gray-600 dark:text-gray-300">Total</div><div class="text-sm font-bold text-green-600 dark:text-green-400">${money(m, l.unit * l.qty)}</div></div><button type="button" class="flex h-8 w-8 items-center justify-center rounded-md text-red-500 transition-colors hover:bg-red-50 hover:text-red-600 dark:hover:bg-red-900/20" data-act="cart-remove" data-id="${l.product.id}" data-testid="cart-item-remove-btn-mobile-${l.product.id}" aria-label="Remove item from cart" title="Remove from cart">${lucide('trash2', { cls: 'h-[18px] w-[18px]' })}</button></div>
      </div></div>`).join('');
  const desktop = lines.map((l, i) => `<tr data-testid="cart-item-row-desktop-${l.product.id}" data-status="in-stock" class="hover:bg-gray-50 dark:hover:bg-gray-700/30 transition-colors ">
      <td class="px-5 py-4 align-top"><div class="flex items-center gap-3"><div class="w-14 h-14 bg-white dark:bg-gray-700 rounded-lg overflow-hidden flex-shrink-0 border border-gray-200 dark:border-gray-600">${img('w-full h-full object-cover rounded-custom', 56)}</div><div class="flex-1 min-w-0"><div class="text-sm font-semibold text-gray-900 dark:text-white truncate">${esc(l.product.name)}</div><div class="text-xs text-gray-500 dark:text-gray-400 mt-1">-</div><div class="text-xs text-gray-400 dark:text-gray-500">Art No: <!---->${esc(l.product.articleNo)}</div></div></div></td>
      <td class=" py-4 align-top"><div class="flex gap-2 items-center"><div class=""><div class="font-bold text-sm text-gray-900 dark:text-white">${money(m, l.unit)}</div><div class="text-[11px] leading-tight text-gray-500 dark:text-gray-400">${esc(l.product.unit)}</div>${l.product.tax ? `<span class="block text-[11px] leading-tight text-gray-500">${l.product.tax}% incl. tax</span>` : ''}</div><button type="button" data-testid="cart-item-price-edit-btn-desktop-${l.product.id}" class="group flex w-8 flex-shrink-0 items-center justify-center rounded-md transition-colors hover:bg-green-50 dark:hover:bg-green-900/20 h-8" aria-label="Edit price" title="Edit price">${lucide('pen', { cls: 'h-[18px] w-[18px] text-gray-500 group-hover:text-green-600 dark:text-gray-400' })}</button></div></td>
      <td class="px-5 py-4 align-top"><div class="flex flex-col items-center gap-1"><div class="flex items-center justify-center gap-1"><span class="text-xs dark:text-gray-500">${esc(l.product.unit)}</span></div><div class="flex flex-col w-full max-w-[160px]"><div class="flex items-center border border-gray-300 dark:border-gray-600 rounded-lg overflow-hidden bg-white dark:bg-gray-800"><button${l.qty <= 1 ? ' disabled=""' : ''} data-act="cart-qty" data-id="${l.product.id}" data-step="-1" data-testid="cart-item-qty-decrement-btn-desktop-${l.product.id}" class="w-10 h-9 text-base flex-shrink-0 flex items-center justify-center text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-semibold border-r border-gray-300 dark:border-gray-600" title="${l.qty <= 1 ? 'Minimum quantity is 1' : 'Decrease quantity'}" aria-label="Decrease quantity">−</button><input type="tel" inputmode="numeric" pattern="\\d*" id="cart-qty-input-desktop-${i}" data-testid="cart-item-qty-input-desktop-${l.product.id}" autocomplete="off" class="flex-1 min-w-0 h-9 text-sm text-center font-medium border-0 focus:outline-none focus:ring-0 text-gray-900 dark:text-white bg-transparent" title="Enter quantity" aria-label="Quantity" value="${l.qty}"><button data-act="cart-qty" data-id="${l.product.id}" data-step="1" data-testid="cart-item-qty-increment-btn-desktop-${l.product.id}" class="w-10 h-9 text-base flex-shrink-0 flex items-center justify-center text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors font-semibold border-l border-gray-300 dark:border-gray-600" title="Increase quantity" aria-label="Increase quantity">+</button></div></div><div class="text-xs text-gray-500 dark:text-gray-400"></div></div></td>
      <td class="px-5 py-4 align-top"><div class="text-base font-bold text-green-600 dark:text-green-400">${money(m, l.unit * l.qty)}</div></td>
      <td class="px-5 py-4 text-center align-top"><button data-act="cart-remove" data-id="${l.product.id}" class="p-2 text-red-600 dark:text-gray-500 hover:text-red-600 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-all" data-testid="cart-item-remove-btn-desktop-${l.product.id}" aria-label="Remove item from cart" title="Remove from cart (can be restored from Deleted Items tab)">${lucide('trash2', { cls: 'w-5 h-5' })}</button></td>
    </tr>`).join('');
  return `<div class="order-cart-tabs-sticky mb-2 lg:mb-4 lg:flex-shrink-0"><div class="flex items-center gap-2 overflow-x-auto py-1 [-ms-overflow-style:none] [scrollbar-width:none] [&amp;::-webkit-scrollbar]:hidden lg:overflow-visible lg:flex-wrap">
      <button type="button" data-testid="order-cart-tab-cart" class="shrink-0 px-3 py-1.5 text-xs font-semibold transition border rounded-lg lg:px-5 lg:py-2.5 lg:text-sm bg-green-600 text-white border-green-600 shadow-sm ">Cart Items</button>
      <button type="button" data-testid="order-cart-tab-deleted" class="shrink-0 px-3 py-1.5 text-xs font-semibold transition border rounded-lg lg:px-5 lg:py-2.5 lg:text-sm bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700/40 ">Deleted Items</button></div></div>
    <div class="order-cart-tab-content md:bg-white md:dark:bg-gray-800 md:rounded-xl md:border md:border-gray-200 md:dark:border-gray-700 overflow-hidden md:shadow-sm"><div class="block md:hidden space-y-3 px-1">${mobile}</div>
      <div class="hidden md:grid grid-cols-12 overflow-x-auto overflow-y-auto rounded-lg border border-gray-200 dark:border-gray-700 max-h-[500px]"><table class="min-w-full text-sm text-gray-700 dark:text-gray-300 col-span-12"><thead class="bg-gray-50 dark:bg-gray-700 sticky top-0 z-10"><tr><th class="text-left px-5 py-3 font-semibold uppercase text-xs w-4/12">Product</th><th class="text-left px-5 py-3 font-semibold uppercase text-xs w-2/12">Price</th><th class="text-center px-5 py-3 font-semibold uppercase text-xs w-3/12">Quantity</th><th class="text-left px-5 py-3 font-semibold uppercase text-xs w-2/12">Total</th><th class="text-center px-5 py-3 font-semibold uppercase text-xs w-1/12">Action</th></tr></thead><tbody class="divide-y divide-gray-200 dark:divide-gray-700">${desktop}</tbody></table></div></div>`;
}

// ── Step 2: payment ──────────────────────────────────────────────────────────────────────
function paymentStep(m, k, t) {
  const total = Math.round(t.grand * 100) / 100;
  const allocated = Math.round(k.selected.reduce((s, id) => s + (Number(k.split[id]) || 0), 0) * 100) / 100;
  const valid = Math.abs(allocated - total) < 0.01;
  const previous = 0; // the receivables ledger (see README → Known differences)
  const paid = allocated;
  const pending = Math.max(0, total - paid);
  const balance = previous + total - paid;
  const methods = paymentMethods(m).map((id) => {
    const d = METHODS[id];
    const on = k.selected.includes(id);
    const card = `<button type="button" aria-disabled="false" data-act="pay-method" data-id="${id}" data-testid="payment-step-method-${id}" data-status="${on ? 'selected' : 'unselected'}" class="w-full flex items-center gap-3 px-3.5 py-3 rounded-xl border text-left transition-all duration-150 group ${on ? 'border-purple-400 bg-purple-50 dark:bg-purple-900/20 shadow-sm ring-1 ring-purple-400/30' : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-gray-300 dark:hover:border-gray-600 hover:shadow-sm'}">
      <div class="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 transition-colors ${on ? 'bg-purple-100 dark:bg-purple-800/50' : 'bg-gray-100 dark:bg-gray-700 group-hover:bg-gray-200 dark:group-hover:bg-gray-600'}">${lucide(d.icon, { cls: `w-4 h-4 ${on ? 'text-purple-600 dark:text-purple-400' : 'text-gray-500 dark:text-gray-400'}` })}</div>
      <div class="flex-1 min-w-0"><div class="flex items-center gap-1.5 flex-wrap"><span class="text-sm font-semibold leading-tight ${on ? 'text-purple-700 dark:text-purple-300' : 'text-gray-800 dark:text-gray-100'}">${d.label}</span>${d.badge ? `<span class="text-[10px] font-semibold px-1.5 py-0.5 rounded-full leading-none ${d.badgeCls}">${d.badge}</span>` : ''}</div><p class="text-xs text-gray-400 dark:text-gray-500 mt-0.5 truncate">${d.desc}</p></div>
      <div class="w-4.5 h-4.5 w-[18px] h-[18px] rounded border-2 flex-shrink-0 flex items-center justify-center transition-all ${on ? 'border-purple-500 bg-purple-500' : 'border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800'}">${on ? lucide('circle-check', { cls: 'w-3 h-3 text-white', stroke: 3 }) : ''}</div></button>`;
    const v = k.split[id];
    const input = on ? `<div class="mx-0.5 px-3.5 pb-3 pt-0 -mt-1 rounded-b-xl border-x border-b border-purple-200 dark:border-purple-700/50 bg-purple-50/60 dark:bg-purple-900/10"><div class="flex items-center gap-2 mt-2.5 mb-1"><span class="text-[11px] text-gray-500 dark:text-gray-400 whitespace-nowrap shrink-0">${d.input}</span><div class="relative flex-1"><span class="absolute left-2.5 top-1/2 -translate-y-1/2 text-xs text-gray-400 dark:text-gray-500 font-medium pointer-events-none select-none">${m.currency}</span><input type="number" inputmode="decimal" min="0" step="1" placeholder="0" data-pay-amount="${id}" data-testid="payment-step-split-amount-input-${id}" class="w-full pl-7 pr-3 py-1.5 text-sm font-semibold rounded-lg border border-purple-200 dark:border-purple-700/60 bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-purple-400 dark:focus:ring-purple-500 transition [appearance:textfield] [&amp;::-webkit-outer-spin-button]:appearance-none [&amp;::-webkit-inner-spin-button]:appearance-none" value="${typeof v === 'string' ? esc(v) : Number.isInteger(v) ? v : Number(v || 0).toFixed(2)}"></div></div></div>` : '';
    return `<div>${card}${input}</div>`;
  }).join('');
  const P = `${m.currency}<!---->${NB}<!---->`;
  const balanceCard = balance < 0
    ? { box: 'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-700/50', tone: 'text-emerald-600 dark:text-emerald-400', title: 'Advance', value: `<div class="text-sm font-bold tabular-nums text-emerald-700 dark:text-emerald-300">+${m.currency}${NB}${amount(-balance)}</div>`, note: 'Advance after this order' }
    : balance > 0
      ? { box: 'bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-700/50', tone: 'text-amber-600 dark:text-amber-400', title: 'Total Outstanding', value: `<div class="text-sm font-bold tabular-nums text-amber-700 dark:text-amber-300">${m.currency}${NB}${amount(balance)}</div>`, note: 'After this order' }
      : { box: 'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-700/50', tone: 'text-emerald-600 dark:text-emerald-400', title: 'Balance', value: '<div class="text-sm font-bold tabular-nums text-emerald-700 dark:text-emerald-300"><span class="inline-flex items-center justify-center rounded-full bg-emerald-100 px-2.5 py-0.5 text-[11px] font-bold uppercase tracking-wide text-emerald-700">Settled</span></div>', note: 'Fully settled' };
  const remaining = Math.round((total - allocated) * 100) / 100;
  return `<div class="md:bg-white md:dark:bg-gray-800 md:rounded-xl md:border md:border-gray-200 md:dark:border-gray-700 md:shadow-sm overflow-hidden flex flex-col h-full">
    <div class="px-5 py-4 border-b border-gray-100 dark:border-gray-700 flex-shrink-0"><h3 class="text-base font-semibold text-gray-900 dark:text-white">Choose Payment Method</h3><p class="text-sm text-gray-500 dark:text-gray-400 mt-0.5">Select how you'd like to pay for this order</p></div>
    <div class="flex-1 min-h-0"><div class="flex flex-col h-full">
      <div class="mx-5 mt-4 grid grid-cols-3 gap-2 flex-shrink-0">
        <div class="rounded-xl border px-3 py-2.5 text-center bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700"><div class="text-[9px] font-bold uppercase tracking-widest mb-1 text-gray-400 dark:text-gray-500">Previous Outstanding</div><div class="text-sm font-bold text-gray-800 dark:text-gray-100 tabular-nums">${P}${amount(previous)}</div><div class="text-[10px] text-gray-400 dark:text-gray-500 mt-0.5">Before this order</div></div>
        <div class="rounded-xl bg-sky-50 dark:bg-sky-900/20 border border-sky-200 dark:border-sky-700/50 px-3 py-2.5 text-center"><div class="text-[9px] font-bold text-sky-600 dark:text-sky-400 uppercase tracking-widest mb-1">This Order</div><div class="text-sm font-bold text-sky-700 dark:text-sky-300 tabular-nums">${P}${amount(total)}</div><div class="text-[10px] text-gray-400 dark:text-gray-500 mt-0.5">${pending > 0 ? `${m.currency}${NB}${amount(pending)} pending` : `${m.currency}${NB}${amount(paid)} paid now`}</div></div>
        <div class="rounded-xl border px-3 py-2.5 text-center ${balanceCard.box}"><div class="text-[9px] font-bold uppercase tracking-widest mb-1 ${balanceCard.tone}">${balanceCard.title}</div>${balanceCard.value}<div class="text-[10px] text-gray-400 dark:text-gray-500 mt-0.5">${balanceCard.note}</div></div>
      </div>
      <div class="mx-5 mt-4 mb-3 flex items-center justify-between px-3.5 py-2.5 rounded-xl bg-purple-50 dark:bg-purple-900/20 border border-purple-300 dark:border-purple-600/50 flex-shrink-0"><div class="flex items-center gap-2">${lucide('layers', { cls: 'w-3.5 h-3.5 text-purple-600 dark:text-purple-400 flex-shrink-0' })}<span class="text-sm font-semibold text-purple-700 dark:text-purple-300">Split Payment</span><span class="text-[10px] text-purple-500 dark:text-purple-400">— select methods &amp; enter amounts</span></div><button type="button" aria-label="Exit split mode" data-testid="payment-step-split-mode-exit-btn" class="p-1 rounded-lg hover:bg-purple-100 dark:hover:bg-purple-800/40 text-purple-500 dark:text-purple-400 transition-colors">${lucide('x', { cls: 'w-4 h-4' })}</button></div>
      <div class="flex-1 min-h-0 px-5 py-3 space-y-2 overflow-y-auto [&amp;::-webkit-scrollbar]:hidden [scrollbar-width:none] [-ms-overflow-style:none]">${methods}</div>
      ${k.selected.length ? `<div class="mx-5 mb-3 px-3.5 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/60 flex-shrink-0"><div class="flex items-center justify-between mb-1.5"><span class="text-[11px] text-gray-500 dark:text-gray-400 font-medium">Allocated</span><span class="text-xs font-bold tabular-nums ${valid ? 'text-green-600 dark:text-green-400' : 'text-gray-700 dark:text-gray-200'}">${P}${amount(allocated)}<span class="font-normal text-gray-400 dark:text-gray-500 mx-1">/</span>${P}${amount(total)}</span></div>
        <div class="w-full h-1.5 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden mb-2"><div class="h-full rounded-full transition-all duration-300 ${valid ? 'bg-green-500' : 'bg-purple-500'}" style="width: ${total > 0 ? Math.min(100, (allocated / total) * 100) : 0}%;"></div></div>
        <div class="flex items-center justify-between"><span class="text-[11px] font-medium ${valid ? 'text-green-600 dark:text-green-400' : allocated > 0.01 ? 'text-amber-600 dark:text-amber-400' : 'text-gray-500 dark:text-gray-400'}">${valid ? '✓ Fully allocated' : allocated > 0.01 ? `⚠ Partial — ${m.currency}${NB}${amount(remaining)} remaining` : `Remaining: ${m.currency}${NB}${amount(remaining)}`}</span><button type="button" data-act="pay-equal" data-testid="payment-step-equal-split-btn" class="flex items-center gap-1 text-[11px] text-gray-400 hover:text-purple-600 dark:text-gray-500 dark:hover:text-purple-400 transition-colors">${lucide('rotate-ccw', { cls: 'w-3 h-3' })}Equal split</button></div></div>` : ''}
      <div class="px-5 py-3 border-t border-gray-100 dark:border-gray-700/60 flex items-center gap-1.5 flex-shrink-0">${lucide('shield-check', { cls: 'w-3.5 h-3.5 text-gray-400 dark:text-gray-500 flex-shrink-0' })}<span class="text-[11px] text-gray-400 dark:text-gray-500">All transactions are secured and encrypted</span></div>
    </div></div></div>`;
}

/** The whole modal body. `k` is the checkout state: { step, split, selected }. */
export function renderCart(m, k, customer, lines) {
  const t = cartTotals(m, lines);
  const pay = k.step === 1;
  const direct = m.appProp.directDeliveryEnabled === true;
  const main = pay ? paymentStep(m, k, t) : cartStep(m, lines);
  const confirm = pay
    ? `<button data-act="cart-place" data-testid="order-cart-confirm-btn" class="h-12 w-full bg-green-600 hover:bg-green-700 text-white rounded-lg disabled:bg-gray-300 disabled:cursor-not-allowed font-bold text-base shadow-md hover:shadow-lg transition-all" title="Confirm and place order" aria-label="Place Order">Place Order</button>${direct ? `<button type="button" data-testid="order-cart-direct-delivery-btn" class="mt-2 flex h-12 w-full items-center justify-center gap-2 rounded-lg border border-green-600 bg-white text-base font-bold text-green-700 shadow-sm transition-all hover:bg-green-50 hover:shadow-md disabled:cursor-not-allowed disabled:border-gray-300 disabled:bg-gray-100 disabled:text-gray-400 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-green-900/20" title="Create this order and complete delivery immediately" aria-label="Complete direct delivery">${lucide('package-check', { cls: 'h-5 w-5' })}Complete Direct Delivery</button>` : ''}`
    : '<button data-act="cart-next" data-testid="order-cart-confirm-btn" class="h-12 w-full bg-green-600 hover:bg-green-700 text-white rounded-lg disabled:bg-gray-300 disabled:cursor-not-allowed font-bold text-base shadow-md hover:shadow-lg transition-all" title="Proceed to next step" aria-label="NEXT →">NEXT →</button>';
  const extras = pay ? '' : `<div class="border-t border-gray-200 dark:border-gray-700 px-4 py-3 lg:px-6 lg:py-4 space-y-2 lg:space-y-3 flex-shrink-0">
      <div data-testid="order-cart-offers-card" class="flex items-center justify-between px-3 py-2 lg:p-3 border border-gray-200 dark:border-gray-700 rounded-lg cursor-pointer hover:border-green-500 hover:bg-green-50 dark:hover:bg-green-900/10 transition-all"><div class="flex items-center gap-2">${lucide('tag', { cls: 'w-3.5 h-3.5 lg:w-4 lg:h-4 text-gray-500 dark:text-gray-400' })}<span class="text-xs lg:text-sm font-medium text-gray-700 dark:text-gray-300">Offers</span></div><span class="text-xs lg:text-sm text-green-600 font-medium hover:underline">view</span></div>
      <div data-testid="order-cart-comment-card" class="flex items-center justify-between px-3 py-2 lg:p-3 border border-gray-200 dark:border-gray-700 rounded-lg cursor-pointer hover:border-green-500 hover:bg-green-50 dark:hover:bg-green-900/10 transition-all"><div class="flex items-center gap-2">${lucide('message-square', { cls: 'w-3.5 h-3.5 lg:w-4 lg:h-4 text-gray-500 dark:text-gray-400' })}<span class="text-xs lg:text-sm font-medium text-gray-700 dark:text-gray-300">Add Comment</span></div></div></div>`;
  const mobileButtons = pay
    ? `<div class="grid min-w-0 flex-1 gap-1.5 grid-cols-${direct ? 2 : 1}"><button data-act="cart-place" class="h-11 min-w-0 whitespace-nowrap rounded-lg bg-green-600 px-2 text-xs font-bold text-white shadow-md transition-all hover:bg-green-700 hover:shadow-lg disabled:cursor-not-allowed disabled:bg-gray-300" title="Confirm and place order" aria-label="Place Order" data-testid="mobile-summary-confirm-btn">Place Order</button>${direct ? `<button type="button" class="flex h-11 min-w-0 items-center justify-center gap-1 whitespace-nowrap rounded-lg border border-green-600 bg-white px-1.5 text-xs font-bold text-green-700 shadow-sm transition-all hover:bg-green-50 disabled:cursor-not-allowed disabled:border-gray-300 disabled:bg-gray-100 disabled:text-gray-400 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-green-900/20" title="Create this order and complete delivery immediately" aria-label="Complete direct delivery" data-testid="mobile-summary-direct-delivery-btn">${lucide('package-check', { cls: 'h-4 w-4' })}Direct Delivery</button>` : ''}</div>`
    : '<div class="grid min-w-0 flex-1 gap-1.5 grid-cols-1"><button data-act="cart-next" class="h-11 min-w-0 whitespace-nowrap rounded-lg bg-green-600 px-2 text-xs font-bold text-white shadow-md transition-all hover:bg-green-700 hover:shadow-lg disabled:cursor-not-allowed disabled:bg-gray-300" title="Proceed to next step" aria-label="NEXT →" data-testid="mobile-summary-confirm-btn">NEXT →</button></div>';
  return `<button data-act="cart-close" class="absolute right-2 w-8 h-8 bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-full flex items-center justify-center transition-all hover:scale-110 active:scale-95 z-50" aria-label="Close cart" title="Close" style="top: 0.5rem;">${lucide('x', { cls: 'w-4 h-4' })}</button>
    <div class="order-cart-inner w-full flex flex-col gap-3 flex-1 min-h-0 md:overflow-y-auto">
      <div class="order-cart-product-list flex-1 min-w-0">${main}</div>
      <div class="order-cart-summary-desktop hidden md:block w-full"><div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 shadow-md overflow-hidden lg:sticky lg:top-0 flex flex-col">
        <div class="bg-gradient-to-r from-gray-50 to-gray-100 dark:from-gray-700 dark:to-gray-800 px-4 py-3 lg:px-5 lg:py-3 border-b border-gray-200 dark:border-gray-600 flex-shrink-0"><div class="flex items-center justify-between gap-2"><div class="flex items-center gap-2 min-w-0">${pay ? `<button data-act="cart-back" data-testid="order-cart-step-back-btn" class="p-1 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-lg transition-colors flex-shrink-0" aria-label="Back">${lucide('chevron-left', { cls: 'w-4 h-4 text-gray-600 dark:text-gray-300' })}</button>` : ''}<div class="text-sm font-bold text-gray-900 dark:text-white truncate">${esc(m.label)} Summary</div></div>${stepper(k.step)}</div></div>
        <div class="flex flex-col flex-1">${customerCard(customer)}${financials(m, t)}${extras}<div class="border-t border-gray-200 dark:border-gray-700 px-4 py-3 lg:px-6 lg:py-4 flex-shrink-0">${confirm}</div></div>
      </div></div>
    </div>
    <div class="md:hidden flex-shrink-0 bg-white dark:bg-gray-800 z-30"><div class="px-1 py-2 space-y-2">
      <button data-testid="mobile-summary-expand-toggle" data-status="collapsed" class="w-full flex items-center justify-between px-3 py-2 bg-gray-50 dark:bg-gray-700/50 rounded-lg border border-gray-200 dark:border-gray-700 active:bg-gray-100 dark:active:bg-gray-600 transition-colors"><div class="flex items-center gap-2">${lucide('shopping-cart', { cls: 'w-4 h-4 text-green-600' })}<span class="text-sm font-bold text-gray-900 dark:text-white">Order Summary</span></div>${lucide('chevron-up', { cls: 'w-4 h-4 text-gray-500 dark:text-gray-400' })}</button>
      <div class="flex items-stretch gap-1.5"><button data-act="${pay ? 'cart-back' : 'cart-close'}" class="h-11 flex items-center justify-center px-3 border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-600 dark:text-gray-300 rounded-lg transition-all flex-shrink-0" aria-label="${pay ? 'Back to previous step' : 'Back to products'}" title="${pay ? 'Back' : 'Back to products'}" data-testid="mobile-summary-back-btn">${lucide('chevron-left', { cls: 'w-4 h-4' })}</button>${mobileButtons}</div>
    </div></div>`;
}
